### ISSUE TITLE
Replace the "exclusion" range

### ISSUE THREAD

**Issue by hackerfactor** [c2pa-org/public-draft#29] opened 2021-11-05 20:49 UTC
Section 9.4.2 and 17.5.1 defines an exclusion range. This permits computing a checksum and storing it, without modifying the checksum based on the data being added.  In addition, it defines a "pad" range. This way, you can compute the checksum and then add in the data. If the data changes size, then the pad can be used to cover an change in the data size.

I'm wondering why you don't use the same appoached used by the ICC Profile:
Compute the checksum over the entire range and only (automatically exclude the bytes used for storing the checksum. This way, you don't need to explicitly define an exclusion range.

In addition, the padding can be part of the checksum storage. Fixed-length checksums (e.g., sha256) do not need padding. Variable-length signatures (e.g., x509) can have null bytes as padding at the end of the checksum. Alternately, the checksum value can start with a two-byte length and then include the checksum. In this case, the jumbf or cbor item has a length for the hash value that covers the two-byte encoded length, binary hash, and any padding (all in one field).

Having a large exclusion range, such as one that excludes the XMP and adjaced JUMBF (as mentioned in 17.5.1) permits an attacker to easily modify the entire JUMBF block or modify other content without any alterations.

**Comment by lrosenthol** [comment] 2021-11-05 20:54
>I'm wondering why you don't use the same appoached used by the ICC Profile:

If the only thing that would be excluded were the JUMBF block (aka C2PA Manifest Store), then you are correct, we could indeed take that approach.  And, in the upcoming update to the draft specification, you will find a case where we do leverage that.

However, we have examples/use-cases where the claim generator wishes to exclude other areas of the asset that it doesn't want included in the hash - which is also why the ranges are an array.

**Comment by lrosenthol** [comment] 2021-12-14 19:58
Duplicate of #37 - closing

**Closed by lrosenthol** 2021-12-14 19:58 UTC
Labels: duplicate
